/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./../registered/app-card/index.vue')['default']
    AppComment: typeof import('./../registered/app-comment/index.vue')['default']
    AppFlex: typeof import('./../registered/app-flex/index.vue')['default']
  }
}
