/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./../registered/app-card/index.vue')['default']
    AppCardBlank: typeof import('./../registered/AppCardBlank.vue')['default']
    AppComment: typeof import('./../registered/AppComment.vue')['default']
    AppFlex: typeof import('./../registered/app-flex/index.vue')['default']
    AppImage: typeof import('./../registered/AppImage.vue')['default']
    AppImage2: typeof import('./../registered/AppImage2.vue')['default']
    AppPlayground: typeof import('./../registered/AppPlayground.vue')['default']
    AppRead: typeof import('./../registered/AppRead.vue')['default']
    AppVSCode: typeof import('./../registered/AppVSCode.vue')['default']
  }
}
